include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-gKIl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wtc-list-remove-fn-afe8b51c-193d-4caf-b3b4-4fcf6d54e831
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-gKIl
  environment:
    name: wtc-list-remove-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-09T18:46:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wtc-list-remove-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: wtc-list-remove-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wtc-list-remove-fn-afe8b51c-193d-4caf-b3b4-4fcf6d54e831
      namespace: default
  requestsPerPod: 10000
  resources: {}
