apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 027a9b10-9465-4f9c-bcb4-df85824ef7e3
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: watch-list-remove-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/remove
    tls: ""
  method: ""
  methods:
  - DELETE
  prefix: ""
  relativeurl: /watch_list/remove
